// Skill library router — search/load the staged .skill-src library as native model tools.
//
// Why: the session skill catalog is injected into every model request, so resident
// skills cost tokens on every turn. Keeping the library OUT of the catalog and
// reachable through two tools moves that cost to "paid only when used".
//
// Two runtimes consume this one implementation; only the registration seam differs:
//   1. Durable DSH plugin package — this file as-is.
//   2. Dynamic Cordis plugin — session-package.js, generated by build-session-package.mjs,
//      which re-binds `harness.defineTool` / `harness.registerTool` in front of the same code.
// `buildSkillRouterTools` takes its defineTool from the scope, so both seams work unchanged.
//
// PORTABILITY RULE (learned the hard way, 2026-09-23): this file must not depend on
// which `defineTool` it receives. A dev-only shim once sat in the package's own
// node_modules and shadowed @deepseek-ai/dsh-tools, so `defineTool` became an identity
// function, the author DSL (`output.schema: { type: 'json' }`) reached the tool registry
// uncompiled, and the whole plugin tree refused to load:
//   unsupported JSON schema: schema.type must be one of object/array/string/number/integer/boolean/null
// Hence: parameters are built locally in compiled JSON Schema shape, and every schema
// literal below is already valid JSON Schema. `defineTool` then only attaches behaviour.

const MAX_LISTED = 8
const DEFAULT_DESC = 220
const LOAD_CAP = 120000

/**
 * Build a registry-ready tool definition without relying on the runtime's defineTool.
 *
 * `parameters` is accepted in either shape and normalized to standard JSON Schema, so
 * the result is registration-safe whether the runtime compiles schemas or passes them
 * through untouched:
 *   - author DSL: a property map whose entries may carry the author-only `required: true`;
 *   - already-compiled JSON Schema: an object-rooted schema, passed through unchanged
 *     (re-compiling it would nest the schema under a `type` property).
 *
 * @param definition - tool definition whose `parameters` is one of those two shapes.
 * @returns the same definition with standard-schema `parameters`.
 */
export function definePortableTool(definition) {
  const spec = definition.parameters
  const looksCompiled =
    spec !== null &&
    typeof spec === 'object' &&
    !Array.isArray(spec) &&
    spec.type === 'object' &&
    typeof spec.properties === 'object' &&
    spec.properties !== null
  // Already-compiled schema: pass it through, adding only the strictness the registry
  // expects. Re-compiling it would nest the whole schema under a `type` property.
  if (looksCompiled) {
    return {
      ...definition,
      parameters: {
        ...spec,
        required: Array.isArray(spec.required) ? spec.required : [],
        additionalProperties: spec.additionalProperties ?? false,
      },
    }
  }

  const properties = {}
  const required = []
  for (const [key, value] of Object.entries(spec ?? {})) {
    const emitted = { ...value }
    if (emitted.required === true) {
      delete emitted.required
      required.push(key)
    }
    properties[key] = emitted
  }
  return {
    ...definition,
    parameters: {
      type: 'object',
      properties,
      ...(required.length === 0 ? {} : { required }),
      additionalProperties: false,
    },
  }
}

export const SEARCH_DESCRIPTION =
  'Search every skill available to this agent: the session skill catalog (resident .dsh/skills) plus the ~1000-skill staged library under .skill-src. ' +
  'Plain lowercase keywords, AND-ed across skill name, description and upstream repo. ' +
  'This is how the agent selects its own skills — do not ask the user which one to use. ' +
  'Call it before any non-trivial task, whenever the subject may have a specialized procedure: ' +
  'test authoring, security or dependency review, documentation, deployment, performance, accessibility, a specific framework or protocol. ' +
  'Also call it before telling the user a capability is missing, and before improvising a process you suspect already exists. ' +
  'Returns names, repos, a copies count and absolute SKILL.md paths; load what fits with skill_load.'

export const LOAD_DESCRIPTION =
  'Load the full instructions of one or more skills into context, then follow them. Searches the staged .skill-src library first, then skills already installed under .dsh/skills. ' +
  'Use it right after skill_search, with every skill the task needs in one call — pass `names` (comma-separated) for several, or call it twice. The returned text IS the task instructions, and a skill often points at further files. ' +
  'Also the way to load a skill that is not in the catalog for automatic invocation. ' +
  'Resolve any relative path a skill mentions (scripts/, references/, assets/) against the returned base directory.'

function isRecord(value) {
  return value !== null && typeof value === 'object' && Array.isArray(value) === false
}

function normName(value) {
  let text = String(value ?? '').trim().replace(/\\/g, '/')
  text = text.replace(/^@/, '').replace(/\/SKILL\.md$/i, '').replace(/\/+$/, '')
  const parts = text.split('/')
  return (parts[parts.length - 1] ?? '').trim()
}

function isSafeName(name) {
  return /^[a-z0-9][a-z0-9-]*$/.test(name)
}

/**
 * Normalize one requested skill name into a single string.
 *
 * Multi-name calls reach a tool as any of three shapes depending on the transport, and a
 * bare `["a","b"]` that arrives as the string `'["a","b"]'` silently matches a string
 * branch of a `oneOf` and is then treated as one (nonexistent) skill name. Handling all
 * three here is what makes batch loading robust:
 *   - a real array (direct in-process callers, tests);
 *   - a JSON-encoded array (a stringified argument);
 *   - a plain name, possibly with several names separated by commas, semicolons or newlines.
 */
function splitRequestedNames(value) {
  const out = []
  const push = (entry) => {
    const text = String(entry ?? '').trim()
    if (text !== '') out.push(text)
  }
  const visit = (entry) => {
    if (Array.isArray(entry)) {
      for (const item of entry) visit(item)
      return
    }
    if (entry === null || entry === undefined) return
    const text = String(entry).trim()
    if (text === '') return
    if (text.startsWith('[') && text.endsWith(']')) {
      try {
        const parsed = JSON.parse(text)
        if (Array.isArray(parsed)) {
          visit(parsed)
          return
        }
      } catch {
        /* not JSON after all: fall through and treat it as a literal name */
      }
    }
    if (/[,;\n]/.test(text)) {
      for (const part of text.split(/[,;\n]+/)) push(part)
      return
    }
    push(text)
  }
  visit(value)
  return out
}

function joinPath(dir, child) {
  if (dir === '') return child
  return dir.endsWith('/') ? dir + child : dir + '/' + child
}

function splitLines(text) {
  const parts = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n')
  if (parts.length > 0 && parts[parts.length - 1] === '') parts.pop()
  return parts
}

/** Split one TSV row, honoring double-quoted fields with doubled-quote escaping. */
function splitFields(line) {
  const fields = []
  let current = ''
  let quoted = false
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i]
    if (quoted) {
      if (ch === '"') {
        if (line[i + 1] === '"') {
          current += '"'
          i += 1
        } else {
          quoted = false
        }
      } else {
        current += ch
      }
    } else if (ch === '"') {
      quoted = true
    } else if (ch === '\t') {
      fields.push(current)
      current = ''
    } else {
      current += ch
    }
  }
  fields.push(current)
  return fields
}

/**
 * Normalize an index description. The scanner emits the raw frontmatter value,
 * so a YAML block scalar arrives with its `>`/`|` marker still attached
 * (`>- Runs a Semgrep scan…). Left in place, that marker is just noise the
 * keyword matcher must skip; strip it here so both the model text and the
 * matching see a clean sentence.
 */
function cleanDescription(value) {
  let text = String(value ?? '').replace(/\s+/g, ' ').trim()
  text = text.replace(/^[>|][+-]?\s*/, '')
  if (text.startsWith('"') && text.endsWith('"') && text.length > 1) text = text.slice(1, -1)
  return text.trim()
}

/** skill-index.tsv — rows. Header is `repo  relpath  name  description  files  KB`. */
function parseIndex(text) {
  const rows = []
  for (const line of splitLines(text)) {
    if (line === '') continue
    const fields = splitFields(line)
    const repo = fields[0] ?? ''
    const relpath = (fields[1] ?? '').replace(/\\/g, '/')
    const name = fields[2] ?? ''
    // Skip the header by shape, not by an exact string: the column names may or
    // may not be quoted depending on which writer produced the file.
    if (repo === 'repo' && name === 'name') continue
    if (name === '' || relpath === '') continue
    rows.push({ name, repo, relpath, description: cleanDescription(fields[3]), files: fields[4] ?? '' })
  }
  return rows
}

function tokenize(query) {
  const tokens = []
  const normalized = String(query ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9+#._-]+/g, ' ')
  for (const token of normalized.split(' ')) {
    if (token === '' || tokens.includes(token)) continue
    if (tokens.length >= 12) break
    tokens.push(token)
  }
  return tokens
}

function truncate(text, max) {
  return text.length <= max ? text : text.slice(0, max - 1) + '\u2026'
}

/** The tool runtime requires lossless-JSON return values: no undefined, no live objects. */
function jsonSafe(value) {
  return JSON.parse(JSON.stringify(value ?? null))
}

/**
 * Build the two tool definitions against one plugin context.
 *
 * The definitions are assembled with `definePortableTool`, so they reach the registry
 * as standard JSON Schema. That is what makes them registration-safe regardless of the
 * runtime's own defineTool: `tools.register` validates `output.schema` at registration
 * and compiles `parameters` at execution, and both are already in the enforced subset.
 *
 * @param ctx - Cordis context exposing `fs` (and optionally `skills`).
 * @param register - runtime-specific registration seam: `(toolName, tool) => void`.
 */
export function buildSkillRouterTools(ctx, register) {
  let indexCache = null
  let rootDir = ''
  // name (lowercased) -> copies in the current library. Filled by loadIndex.
  let nameCounts = new Map()

  /** How many library rows share this skill name; >1 means skill_load needs a repo hint. */
  function copiesOf(name) {
    return nameCounts.get(String(name).toLowerCase()) ?? 1
  }

  async function resolveRow(row) {
    const skillFile = joinPath(joinPath(joinPath(rootDir, row.repo), row.relpath), 'SKILL.md')
    const target = await ctx.fs.resolve(skillFile)
    const display = target.displayPath
    const directory = display.slice(0, Math.max(0, display.length - 'SKILL.md'.length))
    return { directory: directory.replace(/[\\/]+$/, ''), path: display }
  }

  /** Walk up from the session cwd to the directory holding .skill-src/skill-index.tsv. */
  async function resolveRoot(cwd) {
    let dir = String(cwd ?? '').replace(/[\\/]+$/, '')
    for (let i = 0; i < 8 && dir !== ''; i += 1) {
      let target
      try {
        target = await ctx.fs.resolve(joinPath(joinPath(dir, '.skill-src'), 'skill-index.tsv'))
      } catch {
        target = undefined
      }
      if (target !== undefined) {
        let info
        try {
          info = await ctx.fs.stat(target)
        } catch {
          info = undefined
        }
        if (info !== undefined && info.type === 'file') {
          const display = target.displayPath
          const parent = display.slice(0, Math.max(0, display.length - 'skill-index.tsv'.length))
          return { root: parent.replace(/[\\/]+$/, ''), indexTarget: target, version: String(info.version) }
        }
      }
      const cut = Math.max(dir.lastIndexOf('/'), dir.lastIndexOf('\\'))
      if (cut <= 0) break
      dir = dir.slice(0, cut)
    }
    return { root: '', indexTarget: undefined, version: '' }
  }

  /** Parse + cache the index; the fs version invalidates the cache when the file changes. */
  async function loadIndex(cwd, signal) {
    const located = await resolveRoot(cwd)
    if (located.root === '') {
      return {
        rows: [],
        root: '',
        error:
          'no .skill-src/skill-index.tsv found above the session workspace ' +
          (String(cwd) === '' ? '(unknown)' : String(cwd)) +
          '. Regenerate it with .skill-src\\scan-skills.ps1',
      }
    }
    rootDir = located.root
    const key = located.root + '|' + located.version
    if (indexCache !== null && indexCache.key === key) return indexCache.value
    const text = await ctx.fs.readText(located.indexTarget, signal)
    const rows = parseIndex(text)
    const counts = new Map()
    for (const row of rows) {
      const key = row.name.toLowerCase()
      counts.set(key, (counts.get(key) ?? 0) + 1)
    }
    nameCounts = counts
    const value = { rows, root: located.root, error: '' }
    indexCache = { key, value }
    return value
  }

  /** Bounded fallback scan for a library skill missing from the index. */
  async function walkForSkill(dir, wanted, budget, depth, signal) {
    if (budget.left <= 0 || depth > 3) return ''
    budget.left -= 1
    let entries
    try {
      entries = await ctx.fs.listDir(await ctx.fs.resolve(dir, { signal }), signal)
    } catch {
      return ''
    }
    for (const entry of entries) {
      if (entry.type === 'directory') {
        const child = joinPath(dir, entry.name)
        if (entry.name.toLowerCase() === wanted) {
          try {
            const probe = await ctx.fs.resolve(joinPath(child, 'SKILL.md'), { signal })
            const info = await ctx.fs.stat(probe, signal)
            if (info !== undefined && info.type === 'file') return child
          } catch {
            /* keep walking */
          }
        }
        const found = await walkForSkill(child, wanted, budget, depth + 1, signal)
        if (found !== '') return found
      } else if (entry.name.toLowerCase() === wanted + '.md') {
        return dir
      }
    }
    return ''
  }

  async function scanForSkill(wanted, signal) {
    if (rootDir === '') return ''
    return await walkForSkill(rootDir, wanted, { left: 120 }, 0, signal)
  }

  const searchTool = definePortableTool({
    name: 'skill_search',
    description: SEARCH_DESCRIPTION,
    parameters: {
      type: 'object',
      properties: {
        query: {
          type: 'string',
          description: 'Keyword(s) describing the task or subject, e.g. "kubernetes helm", "seo", "remotion video", "rust cli".',
        },
        limit: { type: 'integer', description: 'Maximum matches to return (1-40, default 12).' },
        repo: {
          type: 'string',
          description: 'Optional repo filter, matched case-insensitively against the upstream directory name, e.g. "trailofbits" or "microsoft-skills".',
        },
        names_only: { type: 'boolean', description: 'Return only names and repos, with no descriptions, when you just need to see what exists.' },
      },
      required: ['query'],
    },
    output: {
      // Standard JSON Schema, valid whether or not the runtime compiles it.
      schema: { type: 'object', additionalProperties: true },
      render(_args, value) {
        const result = isRecord(value) ? value : {}
        const hits = Array.isArray(result.hits) ? result.hits : []
        const lines = [
          String(result.total) +
            ' match(es) in ' +
            String(result.library) +
            '; showing ' +
            String(hits.length) +
            (result.more === true ? ' (more available)' : ''),
        ]
        for (const hit of hits) {
          lines.push(
            '- ' + String(hit.name) + '  [' + String(hit.repo) + ']' + (String(hit.description) === '' ? '' : '\n    ' + String(hit.description)),
          )
        }
        if (String(result.error) !== '') lines.push('error: ' + String(result.error))
        return [{ type: 'text', text: lines.join('\n') }]
      },
    },
    async execute(args, exec) {
      const input = isRecord(args) ? args : {}
      const limit =
        typeof input.limit === 'number' && Number.isFinite(input.limit) ? Math.max(1, Math.min(40, Math.floor(input.limit))) : 12
      const namesOnly = input.names_only === true
      const descLength = namesOnly ? 0 : DEFAULT_DESC
      const repoFilter = typeof input.repo === 'string' ? input.repo.toLowerCase() : ''
      const query = typeof input.query === 'string' ? input.query : ''
      const cwd = exec.agent === undefined ? '' : String(exec.agent.session.header.cwd)
      const loaded = await loadIndex(cwd, exec.signal)
      if (loaded.rows.length === 0) {
        return jsonSafe({ library: loaded.root, total: 0, shown: 0, hits: [], error: loaded.error === '' ? 'the skill index is empty' : loaded.error })
      }
      const tokens = tokenize(query)
      if (tokens.length === 0 && repoFilter === '') {
        return jsonSafe({ library: loaded.root, total: 0, shown: 0, hits: [], error: 'the query must contain at least one letter or digit' })
      }
      const scored = []
      for (const row of loaded.rows) {
        if (repoFilter !== '' && !row.repo.toLowerCase().includes(repoFilter)) continue
        const nameText = row.name.toLowerCase()
        const descText = row.description.toLowerCase()
        const pathText = (row.repo + '/' + row.relpath).toLowerCase()
        let score = 0
        let nameHits = 0
        let ok = true
        for (const token of tokens) {
          let part = 0
          if (nameText.includes(token)) {
            part += 100
            nameHits += 1
          }
          if (descText.includes(token)) part += 24
          if (pathText.includes(token)) part += 6
          if (part === 0) {
            ok = false
            break
          }
          score += part
        }
        if (!ok) continue
        if (nameText === query.trim().toLowerCase()) score += 400
        scored.push({ row, score, listed: tokens.length > 0 && nameHits === tokens.length ? 1 : 0, nameHits })
      }
      scored.sort((a, b) => {
        if (b.listed !== a.listed) return b.listed - a.listed
        if (b.score !== a.score) return b.score - a.score
        if (b.nameHits !== a.nameHits) return b.nameHits - a.nameHits
        if (a.row.name.length !== b.row.name.length) return a.row.name.length - b.row.name.length
        return a.row.name < b.row.name ? -1 : 1
      })
      const hits = []
      for (const entry of scored.slice(0, limit)) {
        const located = await resolveRow(entry.row)
        hits.push({
          name: entry.row.name,
          repo: entry.row.repo,
          description: descLength === 0 ? '' : truncate(entry.row.description, descLength),
          files: entry.row.files,
          // Several upstreams (context-eng-kit especially) ship one skill under
          // skills/, plugins/<x>/skills/ and antigravity/skills/. Reporting the
          // copy count is what tells the model `copies` is worth disambiguating.
          copies: copiesOf(entry.row.name),
          path: located.path,
          libraryRelative: entry.row.repo + '/' + entry.row.relpath,
        })
      }
      return jsonSafe({
        library: loaded.root,
        query,
        total: scored.length,
        shown: hits.length,
        names_only: namesOnly,
        more: scored.length > hits.length,
        hits,
        error: '',
        note:
          hits.length === 0
            ? 'No library match. Try broader or different keywords, or drop the repo filter.'
            : 'Call skill_load with one exact name to read its full instructions; pass repo too when copies > 1.',
      })
    },
    presentCall(args) {
      const query = String((isRecord(args) ? args.query : '') ?? '')
      return { card: 'generic', title: 'Search skill library: ' + query, kind: 'search', rawInput: query }
    },
  })

  /** Resolve one name (+optional repo hint) to a skill and read it. Never throws. */
  async function loadSkill(rawName, repoHint, cwd, signal, exec) {
    const raw = String(rawName ?? '')
    const wanted = normName(raw)
    const wantedLower = wanted.toLowerCase()
    const wantedRepo = String(repoHint ?? '').trim().toLowerCase()
    const missing = { name: raw, source: '', repo: '', copies: 0, path: '', resourceDir: '', content: '', referenceFiles: [], error: '' }
    if (wanted === '') {
      missing.error = 'a skill name is required'
      return jsonSafe(missing)
    }
    const loaded = await loadIndex(cwd, signal)
    let directory = ''
    let chosen = null
    if (loaded.rows.length > 0) {
      // A name can exist many times in one library (context-eng-kit ships each
      // skill three times over). Pick deterministically instead of by file
      // order: the explicit repo filter first, then the shallowest relpath,
      // which selects `skills/<name>` over `plugins/<x>/skills/<name>`.
      const byName = loaded.rows.filter((row) => row.name.toLowerCase() === wantedLower)
      let candidates = byName
      if (wantedRepo !== '') candidates = candidates.filter((row) => row.repo.toLowerCase().indexOf(wantedRepo) >= 0)
      if (byName.length > 0 && candidates.length === 0) {
        // The index knows this name but not under the requested repo. Scanning
        // the directory tree would defeat the filter by finding it anyway, so
        // stop here and say which repos do have it.
        const repos = [...new Set(byName.map((row) => row.repo))].sort()
        missing.error = 'skill "' + wanted + '" is not in a repo matching "' + wantedRepo + '"; it exists in: ' + repos.join(', ')
        return jsonSafe(missing)
      }
      candidates.sort((a, b) => {
        const depthA = a.relpath.split('/').filter(Boolean).length
        const depthB = b.relpath.split('/').filter(Boolean).length
        if (depthA !== depthB) return depthA - depthB
        if (a.relpath.length !== b.relpath.length) return a.relpath.length - b.relpath.length
        return a.relpath < b.relpath ? -1 : 1
      })
      const winner = candidates[0]
      if (winner !== undefined) {
        chosen = winner
        directory = (await resolveRow(winner)).directory
      }
    }
    if (directory === '' && isSafeName(wantedLower)) directory = await scanForSkill(wantedLower, signal)
    if (directory === '') {
      // Not in the library: fall back to the resident registry, which also covers
      // the bundled skills and any name the filesystem roots did not index.
      const skills = ctx.get('skills')
      if (skills !== undefined) {
        let definition
        try {
          definition = await skills.get(wantedLower, { cwd, signal, scope: exec.agent })
        } catch {
          definition = undefined
        }
        if (definition !== undefined) {
          const resourceBase = definition.resourceBase
          const body = String(definition.content)
          return jsonSafe({
            name: String(definition.name),
            source: 'resident',
            repo: '',
            copies: 1,
            path: definition.path === undefined ? '' : String(definition.path),
            resourceDir: resourceBase !== undefined && resourceBase.kind === 'directory' ? String(resourceBase.path) : '',
            content: truncate(body, LOAD_CAP),
            referenceFiles: [],
            error: body.length > LOAD_CAP ? 'content truncated at ' + String(LOAD_CAP) + ' characters' : '',
          })
        }
      }
      missing.error =
        'no skill named "' +
        wanted +
        '" in the library' +
        (loaded.error === '' ? '' : ' (' + loaded.error + ')') +
        ' or in the resident catalog. Call skill_search to find the exact name.'
      return jsonSafe(missing)
    }
    const skillPath = joinPath(directory, 'SKILL.md')
    let body = ''
    try {
      body = await ctx.fs.readText(await ctx.fs.resolve(skillPath, { signal }), signal)
    } catch (error) {
      missing.path = skillPath
      missing.resourceDir = directory
      missing.error = 'failed to read ' + skillPath + ': ' + String(error)
      return jsonSafe(missing)
    }
    const referenceFiles = []
    try {
      const entries = await ctx.fs.listDir(await ctx.fs.resolve(directory, { signal }), signal)
      for (const entry of entries) {
        if (entry.name.toLowerCase() === 'skill.md') continue
        if (referenceFiles.length >= MAX_LISTED) break
        referenceFiles.push(entry.name + (entry.type === 'directory' ? '/' : ''))
      }
    } catch {
      /* a listing failure is not fatal: the body is what matters */
    }
    const text = body.trim()
    return jsonSafe({
      name: wanted,
      source: 'library',
      repo: chosen === null ? '' : chosen.repo,
      copies: chosen === null ? 0 : copiesOf(chosen.name),
      path: skillPath,
      resourceDir: directory,
      content: truncate(text, LOAD_CAP),
      referenceFiles,
      error: text.length > LOAD_CAP ? 'content truncated at ' + String(LOAD_CAP) + ' characters' : '',
    })
  }

  const loadTool = definePortableTool({
    name: 'skill_load',
    description: LOAD_DESCRIPTION,
    parameters: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'One skill name, e.g. "gh-cli". A full path to a SKILL.md is also accepted. For several skills use names instead.',
        },
        names: {
          type: 'string',
          description: 'Several skill names in one call, separated by commas or newlines, e.g. "test-driven-development, verification-before-completion".',
        },
        repo: {
          type: 'string',
          description: 'Optional upstream repo filter for a name that exists several times (skill_search reports copies > 1), e.g. "superpowers" or "trailofbits". Applies to every name in this call.',
        },
      },
    },
    output: {
      // Standard JSON Schema, valid whether or not the runtime compiles it.
      schema: { type: 'object', additionalProperties: true },
      render(_args, value) {
        const result = isRecord(value) ? value : {}
        if (String(result.loaded) === '') return [{ type: 'text', text: 'No skill was loaded.' }]
        const skills = Array.isArray(result.skills) ? result.skills : []
        const lines = []
        for (const skill of skills) {
          if (String(skill.content) === '') {
            lines.push('Could not load skill "' + String(skill.name) + '": ' + String(skill.error))
            continue
          }
          const reference = Array.isArray(skill.referenceFiles) ? skill.referenceFiles : []
          lines.push(
            '<skill_content name="' + String(skill.name) + '" source="' + String(skill.source) + '">',
            'Base directory for this skill: ' +
              String(skill.resourceDir) +
              '.' +
              (reference.length === 0 ? '' : ' Bundled: ' + reference.join(', ') + '.'),
            'Resolve relative paths (scripts/, references/, assets/) against that base directory before using them.',
            '',
            String(skill.content),
            '</skill_content>',
          )
          if (String(skill.error) !== '') lines.push(String(skill.error))
        }
        return [{ type: 'text', text: lines.join('\n') }]
      },
    },
    async execute(args, exec) {
      const input = isRecord(args) ? args : {}
      const requested = splitRequestedNames([input.name, input.names]).slice(0, MAX_LISTED)
      const repoHint = input.repo
      const cwd = exec.agent === undefined ? '' : String(exec.agent.session.header.cwd)
      const skills = []
      for (const entry of requested) {
        skills.push(await loadSkill(entry, repoHint, cwd, exec.signal, exec))
      }
      const loadedNames = skills.filter((skill) => String(skill.content) !== '').map((skill) => String(skill.name))
      const failed = skills.filter((skill) => String(skill.content) === '').map((skill) => String(skill.name))
      return jsonSafe({
        requested: requested.join(', '),
        loaded: loadedNames.join(', '),
        skills,
        failed: failed.join(', '),
        note:
          loadedNames.length === 0
            ? requested.length === 0
              ? 'No name was given. Pass name for one skill, or names for several.'
              : 'Nothing loaded. Call skill_search first to get exact names.'
            : 'Follow these instructions for the current task; a skill may point at further files under its base directory.',
      })
    },
    presentCall(args) {
      const names = splitRequestedNames([(isRecord(args) ? args.name : ''), (isRecord(args) ? args.names : '')])
      const label = names.length === 0 ? '(none)' : names.join(', ')
      return { card: 'generic', title: 'Load skill ' + label, kind: 'read', rawInput: label }
    },
  })

  register(searchTool.name, searchTool)
  register(loadTool.name, loadTool)
  return { searchTool, loadTool }
}

/** Durable DSH plugin entry: registers both tools on the global tool registry. */
export const name = 'local-skill-router'
export const inject = ['fs', 'tools']

export function apply(ctx) {
  buildSkillRouterTools(ctx, (toolName, tool) => {
    ctx.effect(() => ctx.tools.register(tool), 'skill-router: ' + toolName)
  })
}
